[RESTEASY-2851]Fix Java 2 Security Permission in SseEventSourceScheduler.shutdownNow()
resteasy/resteasy pull request #2689
Opened 2021-03-09 19:40 UTC by jim-krueger

2021-03-18 11:34 UTC, asoldano commented
@jim-krueger , we require all contributions to be made under the terms of the ASL 2.0 License: http://www.apache.org/licenses/LICENSE-2.0 
Do you agree to these terms?

2021-03-18 11:39 UTC, asoldano approved these changes

2021-04-09 19:06 UTC, ronsigal commented
@jim-krueger, do you agree to the terms of the ASL 2.0 License: http://www.apache.org/licenses/LICENSE-2.0?

2022-09-12 20:22 UTC, jim-krueger commented
@ronsigal Wow, missed seeing this for a while sorry.  Yes, I agree to the terms of the ASL 2.0 License.

2022-09-19 23:08 UTC, jamezp requested changes

2022-09-19 23:08 UTC, jamezp commented on resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceScheduler.java
> +           });
For performance sake we should do something like:
```java
if (System.getSecurityManager() == null) {
    scheduledExecutorService.shutdownNow();
} else {
    AccessController.doPrivileged(new new PrivilegedAction<Void>() {
        @Override
        public Void run() {
            scheduledExecutorService.shutdownNow();
            return null;
        }
    });
}
```

2022-09-21 00:51 UTC, jamezp commented
Replaced by #3273 3273

2022-09-21 00:51 UTC, closed without merging