[RESTEASY-2866] Ensure proxies implement all intfs
resteasy/Resteasy pull request #2717
Opened 2021-04-02 15:19 UTC by andymc12

This PR resolves JIRA [RESTEASY-2866](https://issues.redhat.com/browse/RESTEASY-2866) by adding all implemented interfaces of the delegate class to the array of interfaces used when building the proxy class.

2021-04-05 19:22 UTC, rsearls commented
Please provide a integration test as well in order to confirm this change has not broken any other code.

2021-04-05 19:27 UTC, rsearls requested changes
Please provide a integration test as well in order to confirm this change has not broken any other code.

2021-04-06 14:04 UTC, andymc12 commented
Hi @rsearls - thanks for the review.  I added a new integration test that casts the proxy injected into `@Context Configuration config` into a RESTEasy-specific interface, `HeaderValueProcessor`.

2021-04-13 08:31 UTC, asoldano approved these changes

2021-04-14 07:54 UTC, merged