RESTEASY-3031 allow http client inject through registration / HTTP2 support via vertx engine
resteasy/resteasy pull request #2946
Opened 2021-11-01 10:43 UTC by liweinan

2021-11-01 20:05 UTC, jamezp requested changes

2021-11-01 20:05 UTC, jamezp commented on resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
> +            httpEngine((ClientHttpEngine) p);
This should break after this:
```java
for (Object p : getProviderFactory().getProviderInstances()) {
     if (p instanceof ClientHttpEngine) {
        httpEngine((ClientHttpEngine) p);
        break;
     }
 }
```

2021-11-01 23:05 UTC, liweinan commented on resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
> +            httpEngine((ClientHttpEngine) p);
yes sir!

2021-11-02 15:14 UTC, jamezp approved these changes

2021-11-02 15:15 UTC, merged