[RESTEASY-3300] Do not append single '&' with empty query parameters
resteasy/resteasy pull request #3522
Opened 2023-03-17 10:09 UTC by Dkafetzis

Fixed this Jira Issue (https://issues.redhat.com/browse/RESTEASY-3300) and added an integration test for this case

2023-03-31 16:37 UTC, jamezp requested changes
We could actually test this with standard API's rather than internal ones. We could use a `ContainerRequestFilter` and get the URI from there to check. In some ways this would be the preferred way IMO.

If we want to stick with using internal API's we should have a method like:
```java
private static Client createClient(final String expectedQuery) {
    ResteasyClientBuilder builder = (ResteasyClientBuilder) ClientBuilder.newBuilder();
    ResteasyClient client = builder.httpEngine(new ClientHttpEngine() {
        @Override
        public Response invoke(Invocation request) {
            Assert.assertEquals(expectedQuery, ((ClientInvocation) request).getUri().getQuery());
            return new AbortedResponse(null, new ServerResponse());
        }

        @Override
        public SSLContext getSslContext() {
            return null;
        }

        @Override
        public HostnameVerifier getHostnameVerifier() {
            return null;
        }

        @Override
        public void close() {
        }
    }).build();
}
```
This would avoid us repeating similar patterns in the test.

This is a little OT for this PR, but I want to remove the usages of `ResteascyClientBuilder` and the `ResteasyClient` in the test suite where we can. We should be using standard API's for this as they are available.

2023-03-31 16:37 UTC, jamezp commented on testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/RequestNamedQueryParameterTest.java
> +            client.target("http://a.place.org").proxy(SomeResource.class).methodWithLists(List.of(), List.of(), List.of());
We should use localhost in all the places here. While this shouldn't be resolved given the above, this is a potential exploit point.

2023-04-03 14:11 UTC, Dkafetzis commented
@jamezp Changes implemented, waiting for review.

2023-04-04 00:11 UTC, jamezp commented
/retest

2023-04-05 09:35 UTC, Dkafetzis commented
@jamezp should be fine now.

2023-04-20 08:06 UTC, Dkafetzis commented
@jamezp All tests passed, I think we can merge this.

2023-04-20 16:42 UTC, jamezp approved these changes

2023-04-20 17:16 UTC, jamezp commented
replaced by #3570

2023-04-20 17:16 UTC, closed without merging