[RESTEASY-3324] Enable redirects using property.
resteasy/resteasy pull request #3710
Opened 2023-07-18 08:15 UTC by The-Huginn

https://issues.redhat.com/browse/RESTEASY-3324

2023-07-18 14:35 UTC, jamezp commented
/ok-to-test

2023-07-18 16:49 UTC, jamezp requested changes
This would also need to be added to the documentation in the `RESTEasy_Client_Framework.xml` in the `docbook` directory as well.

2023-07-18 16:49 UTC, jamezp commented on resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
> +    String unableToSetFollowRedirects();
Given the comment below we likely don't need this.

2023-07-18 16:49 UTC, jamezp commented on resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
> +        }
This isn't quite right. We need to remove this whole method and check the property in the `build()` method. In the `build()` method it should just look something like:

```java
final Object localFollowRedirects = config.getProperty(PROPERTY_FOLLOW_REDIRECTS);
if (localFollowRedirects != null) {
    followRedirects = Boolean.parseBoolean(String.valueOf(localFollowRedirects));
}
```

2023-07-18 16:49 UTC, jamezp commented on resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
> +    public static final String PROPERTY_FOLLOW_REDIRECTS = "org.jboss.resteasy.jaxrs.client.follow-redirects";
We have started to change the prefix we use. This should be something like `dev.resteasy.client.follow.redirects`.

2023-07-19 15:11 UTC, The-Huginn commented
Currently I assume, the property has higher priority. Is that expected or do I add additional logic to allow overriding property by `setFollowRedirects()`?

2023-07-19 18:50 UTC, jamezp commented
> Currently I assume, the property has higher priority. Is that expected or do I add additional logic to allow overriding property by `setFollowRedirects()`?

It's a tough one, but yes we are saying the property wins. If a user did something like:
```
ResteasyClientBuilder().setFollowRedirects(false)
    .property("dev.resteasy.client.follow.redirect", "true");
```

The latter would win. However, I think that's okay as then the user doesn't need to use the `ResteasyClientBuilder` directly.

2023-08-02 22:44 UTC, jamezp approved these changes

2023-08-02 22:44 UTC, merged