6.2.4.final  bootable jar
resteasy/resteasy pull request #4060
Opened 2024-03-04 12:48 UTC by tommaso-borgato

2024-03-04 16:26 UTC, fabiobrz requested changes
Hi @tommaso-borgato - I went through the changes and dropped a couple of minor comments.
BTW - Looking at the original [PR that introduced the changes originally](https://github.com/resteasy/resteasy/pull/2558) I noticed you've not documented the changes in the README, and IIUC also the filtered tests seem to miss some comments about the reason for the exclusion. WDYT?

2024-03-04 16:26 UTC, fabiobrz commented on pom.xml
>          <version.org.wildfly.plugins.wildfly-maven-plugin>4.0.0.Final</version.org.wildfly.plugins.wildfly-maven-plugin>
I guess this should be bumped as well.

2024-03-04 16:26 UTC, fabiobrz commented on pom.xml
>          <version.org.wildfly.galleon-plugins>6.4.2.Final</version.org.wildfly.galleon-plugins>
And maybe these Galleons dependency will need to be updated according to those of the wildfly-maven-plugin and wildfly-jar-maven-plugin? Not sure though, but I think this should be worth checking.

2024-03-25 17:43 UTC, tommaso-borgato commented
We are going to use https://github.com/tommaso-borgato/Resteasy/tree/6.2.4.Final--bootable-jar

2024-03-25 17:45 UTC, tommaso-borgato commented
We are going to use https://github.com/tommaso-borgato/Resteasy/tree/6.2.4.Final--bootable-jar

2024-03-25 17:45 UTC, closed without merging