[RESTEASY-3500] The ExceptionHandler sets the media type of an except ion to text/html
resteasy/resteasy pull request #4203
Opened 2024-06-04 08:09 UTC by Dkafetzis

https://issues.redhat.com/browse/RESTEASY-3500

2024-06-04 16:04 UTC, jamezp requested changes
The `SecureProcessingTest` and `SecureProcessing2Test` tests need to be updated. The response has `/` assumed to be escaped with `&#x2F;`.

2024-06-07 00:40 UTC, jamezp commented
Sorry @Dkafetzis you'll need to add:
```java
@RequiresModule(value = "org.jboss.resteasy.resteasy-core", minVersion = "7.0.0.Alpha3")
```
On the test methods:
- `SecureProcessingTest.testSecurityTrueDTDsTrueExpansionTrueWithApacheLinkMessage()`
- `SecureProcessing2Test.testSecurityDefaultDTDsTrueExpansionTrueWithApacheLinkMessage()`

That should fix the failing tests.

2024-06-07 10:00 UTC, Dkafetzis commented
@jamezp Done, thanks for the correction.

2024-06-07 15:36 UTC, jamezp approved these changes

2024-06-07 15:55 UTC, merged